---
- host: all
  become: yes
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      notify:
      - restart htpd
  handlers:
    - name: restart ntp
      service: name=ntpd state=restarted