# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos7-py3.8"

  config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"

  config.vm.network "public_network"#, ip: "172.16.7.10"

  # config.vm.provision "shell", inline: <<-SHELL
  #   yum install epel-release -y
  #   yum install gcc wget -y
  #   yum groupinstall "Development tools" -y
  #   yum install zlib-devel bzip2-devel openssl openssl-devel ncurses-devel sqlite-devel -y
  #   cd /tmp && wget http://my.jiang2021.cn:56102/download/python/Python-3.8.12.tgz
  #   chmod 755 /vagrant/Python-3.8.12.tgz
  #   tar xf /vagrant/Python-3.8.12.tgz -C /tmp/ 
  #   cd /tmp/Python-3.8.12/
  #   ./configure --prefix=/usr/local/python3.8 && make && make install
  #   mv `which python` `which python`2.7.5
  #   sed -i "s@/usr/bin/python@/usr/bin/python2.7@g" `which yum`
  #   sed -i "s@/usr/bin/python@/usr/bin/python2.7@g" /usr/libexec/urlgrabber-ext-down
  #   yum install -y  telnet vim tree net-tools
  #   ln -s /usr/local/python3.8/bin/python3 /bin/python
  #   ln -s /usr/local/python3.8/bin/pip3 /bin/pip
  #   python -V 
  #   pip -V
  #   # set ssh key for mac && win
  #   echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd2IX7HndNRsqEjsFhow+K52eO4L7Vjx5Ce54l0GZwcsiwCp3tAv39KiV48wMioqRoMUCPVZsfTgy8v/9eKNiSdW0NAhUaA8Y0wzSFUcZbeTvGIdJCaBKLpD6ehKtEwCjoZBWpaMlT2/WfGsSktCIaMwS2m3GlT+Rp94fs6AzpeaM9yO2Z7bWvIcDzff5Wc9n28U75NhXzuEDVvAyDeN8GkIAxnHTLHvWwQx8fHWun6NzNppbiXrD5jdntcXFeG6f9kWwRC8U+VMpTs8tWWAKr8z0TNiS3JpF1yfBvCACEs8go/l+FU82n4ilzNNmUqUBFMGdCYayxVG93sRa0YiiZeigm9pmN+kYe61HiDsUEgHFe0bCnbkaUyPJVhyruo520H4sWHU6k+w1tw3Jqy51nOmPYdLpN1lRE3NazKaODExoWG+So14Fz1qaBA+rN7UQWm+YYtglJllTfFYDlnnx30wVtOwb/2v4IuhxyuLEOxhMKN32TJFtP6piKzwcqUqs= Vixtel@DESKTOP-UNFIOA1" >> /home/vagrant/.ssh/authorized_keys
  #   echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuf+zd/jzUOWSYovhzoKiEB6JWyUnPE5yducO3RDhsAyxRUlnMBvEP43MkOBSGgmdAkhz3kZi9twP/fOX4518/S4FvJo3YC2UILOQVgHbgwNqNZUbPrlbKfVE9uN2ikHW/POOhohWcl0Pb0cwi21a0beZ8yNww1vGErftkVEXoDEK+gDiC7w5qsQ+9nBDhAkSbqvANfMucFkNUgH8O0M/1gpaejPc1S9RbseZxEhuS6A7Cb5NhY8lvlJYvKDzrSf1iNBshZ3MwtjNcYIKBL2jQxLC21QfNxMxgDt7eJMGRbUNAn6vCWrF8zbMqSA0u1sSKzTCJk1pwKhcPUvCaQA6F lijunjiang2012@163.com" >> /home/vagrant/.ssh/authorized_keys
  # SHELL

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
