# -*- mode: ruby -*-
# vi: set ft=ruby :
# on win10, you need `vagrant plugin install vagrant-vbguest --plugin-version 0.21` and change synced_folder.type="virtualbox"
# reference `https://www.dissmeyer.com/2020/02/11/issue-with-centos-7-vagrant-boxes-on-windows-10/`

Vagrant.configure("2") do |config|

    config.vm.box_check_update = false
    config.vm.box = "centos7-py3.8"
    config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"
    config.vm.synced_folder ".", "/vagrant"

    # 创建 master 节点
    config.vm.define "master" do |master|
        master.vm.hostname = "master"
        ip = "172.16.7.10"
        master.vm.network "public_network", ip: ip
        master.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
            vb.name = "master"
        end
        master.vm.provision "shell", path: "install.sh", args: ["master"]
    end

    # 批量创建三个节点，node[1 - 3]
    $num_instances = 3
    $etcd_cluster = "node1=http://172.17.8.101:2380"  # 定义脚本参数
    (1..$num_instances).each do |i|
        config.vm.define "node#{i}" do |node|
            # node.vm.box = "centos/7"
            # node.vm.box_version = "1804.02"
            # config.vm.box = "centos7-py3.8"
            # config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"
            node.vm.hostname = "node#{i}"
                ip = "172.17.6.#{i+10}"
                node.vm.network "public_network", ip: ip
                node.vm.provider "virtualbox" do |vb|
                    vb.memory = "500"
                    vb.cpus = 1
                    vb.name = "node#{i}"
                end
            node.vm.provision "shell", path: "install.sh", args: [i]
            # config.vm.provision "shell", inline: <<-SHELL
            # SHELL
        end
    end
end