Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "4096"
    end

    config.vm.provision "ins_jenkins", type: "shell", inline: <<-SHELL
        # cp /vagrant/jenkins.repo /etc/yum.repos.d/
        # rpm --import /vagrant/jenkins.io.key
        # yum upgrade
        yum install -y epel-release java-11-openjdk-devel wget
        cd /tmp && wget https://mirrors.aliyun.com/jenkins/redhat-stable/jenkins-2.303.3-1.1.noarch.rpm > /dev/null 2>&1
        yum localinstall -y jenkins-2.303.3-1.1.noarch.rpm
        systemctl daemon-reload
        systemctl start jenkins
        /sbin/chkconfig jenkins on
        echo    "####################################################################"
        echo -E "Execute：sudo cat /var/lib/jenkins/secrets/initialAdminPassword \nCopy the automatically-generated alphanumeric password!!"
        echo    ”####################################################################“
    SHELL
end